### ISSUE TITLE
Request: abbreviated output format (version, path)

### ISSUE THREAD

**Issue by cxw42** [perlancar/perl-App-PMUtils#1]
`pminfo` is a nice tool, and just the script name I would have picked myself for the same function :) .  I don't usually need the line count, and the filename pushes the version to the next line on my system.  Would you be willing to add a terse-output mode that shows text without headers or table boxes, just for `version path`?  E.g., `pminfo App::PMUtils` on my system currently yields something that looks like:

    +------------+-------+--------------+--------------------------------------------------------
    ------------------------------------+---------+
    | date       | lines | module       | path                                                                                 
                                    | version |
    +------------+-------+--------------+--------------------------------------------------------
    ------------------------------------+---------+
    | 2019-02-24 | 452   | App::PMUtils | /home/cxw/perl5/perlbrew/perls/perlcygbrew-5.26.2-1/lib/
    site_perl/5.26.2/App/PMUtils.pm | 0.721   |
    +------------+-------+--------------+--------------------------------------------------------
    ------------------------------------+---------+

and I would like terse mode to output:

    0.721 /home/cxw/perl5/perlbrew/perls/perlcygbrew-5.26.2-1/lib/site_perl/5.26.2/App/PMUtils.pm

Thank you for considering this request!

**Comment by perlancar** [comment]
Sorry for the late response, didn't see the notification for this issue until today.

You can use [td](https://metacpan.org/pod/td) to slice and dice the output (and later put the incantation in your script): This is more general and can work with other people who might want to have different set of columns in different order.

    % pminfo `this-mod` App::PMUtils | td select version path
    +---------+------------------------------------------------------------------------------------------+
    | version | path                                                                                     |
    +---------+------------------------------------------------------------------------------------------+
    | 0.140   | /home/s1/perl5/perlbrew/perls/perl-5.34.0/lib/site_perl/5.34.0/Log/Any/Adapter/Screen.pm |
    | 0.735   | /home/s1/perl5/perlbrew/perls/perl-5.34.0/lib/site_perl/5.34.0/App/PMUtils.pm            |
    +---------+------------------------------------------------------------------------------------------+
    
    % pminfo `this-mod` App::PMUtils | td select version path --format text-simple 
    0.140   /home/s1/perl5/perlbrew/perls/perl-5.34.0/lib/site_perl/5.34.0/Log/Any/Adapter/Screen.pm
    0.735   /home/s1/perl5/perlbrew/perls/perl-5.34.0/lib/site_perl/5.34.0/App/PMUtils.pm
